apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nvidia-device-plugin
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: nvidia-device-plugin
      version: 0.17.1
      sourceRef:
        kind: HelmRepository
        name: nvidia-device-plugin
        namespace: flux-system
      interval: 1m
  targetNamespace: kube-system
  install:
    createNamespace: false
    remediation:
      retries: 1
  upgrade:
    remediation:
      retries: 1
  values:
    # Enable compatibility with different runtimes
    runtimeClassName: ""
    # Configure resource limits
    resources:
      limits:
        memory: "128Mi"
      requests:
        cpu: "100m"
        memory: "128Mi"