apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sealed-secrets-controller
  namespace: sealed-secrets
spec:
  releaseName: sealed-secrets-controller
  targetNamespace: sealed-secrets
  interval: 1h # Helm CRD drift detection interval
  timeout: 15m
  chart:
    spec:
      chart: sealed-secrets
      version: 2.17.4
      interval: 10h # Interval for Helm chart updates
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets
        namespace: sealed-secrets
  values:
    # Enable metrics for monitoring
    metrics:
      serviceMonitor:
        enabled: false # Set to true if you want Prometheus monitoring
    
    # Configure the controller
    controller:
      # Additional annotations for the controller pods
      podAnnotations: {}
      
      # Resource limits and requests
      resources:
        limits:
          cpu: 50m
          memory: 128Mi
        requests:
          cpu: 50m
          memory: 128Mi