apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - repository.yaml
  - ollama-pv.yaml
  - ollama-pvc.yaml
  - release.yaml

patches:
  - target:
      kind: PersistentVolumeClaim
      name: ollama-pvc
    patch: |-
      - op: add
        path: /metadata/annotations/kustomize.toolkit.fluxcd.io~1depends-on
        value: ollama/ollama-pv
  - target:
      kind: HelmRelease
      name: ollama