apiVersion: v1
kind: PersistentVolume
metadata:
  name: ollama-local-pv
  labels:
    app: ollama-storage
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  volumeMode: Filesystem
  local:
    path: /data/ollama