apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: open-webui-pipelines-pvc
  namespace: open-webui-pipelines
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: ""
  volumeName: open-webui-pipelines-pv