apiVersion: v1
kind: PersistentVolume
metadata:
  name: open-webui-pipelines-pv
  namespace: open-webui-pipelines
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /var/lib/open-webui-pipelines
    type: DirectoryOrCreate