apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: open-webui
  namespace: open-webui
spec:
  dependsOn:
    - name: ollama
      namespace: ollama
  releaseName: open-webui
  targetNamespace: open-webui
  interval: 1h # Helm CRD drift detection interval
  chart:
    spec:
      chart: open-webui
      interval: 10h # Interval for Helm chart updates
      sourceRef:
        kind: HelmRepository
        name: open-webui
        namespace: open-webui
  values:
    # Disable embedded Ollama since we have a separate Ollama deployment
    ollama:
      enabled: false
    
    # Configure external Ollama URLs - pointing to your existing Ollama service
    ollamaUrls:
      - "http://ollama.ollama.svc.cluster.local:11434"
    
    # Disable pipelines for simpler setup (can be enabled later)
    pipelines:
      enabled: false
    
    # Disable Tika for now
    tika:
      enabled: false

    # Resource configuration
    resources:
      requests:
        cpu: 500m
        memory: 512Mi
      limits:
        cpu: 2
        memory: 4Gi
    
    # Service configuration - using LoadBalancer to match your Ollama setup
    service:
      type: ClusterIP
      port: 5050
      containerPort: 8080
    
    # Persistence for user data and conversations
    persistence:
      enabled: true
      existingClaim: open-webui-pvc

